package esprit.rt.gui;

import java.awt.Color;
import java.awt.Cursor;
import java.awt.Font;
import java.awt.FontFormatException;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author Pingouins de désert
 * 
 */

public class RestaurateurMainMenu extends javax.swing.JFrame {
    Font fBtn, fTitle;
    ArrayList <JLabel> btns;
    /**
     * Creates new form RestaurateurMainMenu
     */
    @SuppressWarnings("empty-statement")
    public RestaurateurMainMenu() throws FontFormatException, IOException {
        this.fBtn = Font.createFont(Font.TRUETYPE_FONT, getClass().getResourceAsStream("/esprit/rt/fonts/franchise_bold.ttf"));
        this.fTitle = Font.createFont(Font.TRUETYPE_FONT, getClass().getResourceAsStream("/esprit/rt/fonts/track.ttf"));
        initComponents();
        btns = new ArrayList <JLabel> ();
        btns.add(btnGestRest);
        btns.add(btnGestRes);
        btns.add(btnGestBP);
        btns.add(btnQuitter);
        title.setFont(fBtn);
        title.setFont(title.getFont().deriveFont(0,128));
        title.setHorizontalAlignment(JLabel.CENTER);
        for (JLabel jl : btns)
        {
            jl.setFont(fBtn);
            jl.setFont(btnGestRes.getFont().deriveFont(0,32));
        }
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        panelBtnGestRest = new javax.swing.JPanel();
        btnGestRest = new javax.swing.JLabel();
        panelBtnGestRes = new javax.swing.JPanel();
        btnGestRes = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        panelBtnPB = new javax.swing.JPanel();
        btnGestBP = new javax.swing.JLabel();
        panelBtnQuitter = new javax.swing.JPanel();
        btnQuitter = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu Principale");
        setResizable(false);

        mainPanel.setBackground(new java.awt.Color(29, 29, 29));
        mainPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnsMouseEntered(evt);
            }
        });

        title.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        title.setForeground(new java.awt.Color(142, 142, 142));
        title.setText("Menu Principale");

        panelBtnGestRest.setBackground(new java.awt.Color(29, 29, 29));
        panelBtnGestRest.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnGestRest.setBackground(new java.awt.Color(255, 255, 255));
        btnGestRest.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        btnGestRest.setForeground(new java.awt.Color(204, 204, 204));
        btnGestRest.setIcon(new javax.swing.ImageIcon(getClass().getResource("/esprit/rt/images/restaurant001.png"))); // NOI18N
        btnGestRest.setText("Gestion des restaurants");
        btnGestRest.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                goToRest(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnsMouseEntred(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnsMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelBtnGestRestLayout = new javax.swing.GroupLayout(panelBtnGestRest);
        panelBtnGestRest.setLayout(panelBtnGestRestLayout);
        panelBtnGestRestLayout.setHorizontalGroup(
            panelBtnGestRestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBtnGestRestLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnGestRest, javax.swing.GroupLayout.PREFERRED_SIZE, 548, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(163, Short.MAX_VALUE))
        );
        panelBtnGestRestLayout.setVerticalGroup(
            panelBtnGestRestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBtnGestRestLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnGestRest)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelBtnGestRes.setBackground(new java.awt.Color(29, 29, 29));
        panelBtnGestRes.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnGestRes.setBackground(new java.awt.Color(255, 255, 255));
        btnGestRes.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        btnGestRes.setForeground(new java.awt.Color(204, 204, 204));
        btnGestRes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/esprit/rt/images/menu001.png"))); // NOI18N
        btnGestRes.setText("Consultation des réservations");
        btnGestRes.setMaximumSize(new java.awt.Dimension(507, 128));
        btnGestRes.setMinimumSize(new java.awt.Dimension(507, 128));
        btnGestRes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGestResMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnsMouseEntred(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnsMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelBtnGestResLayout = new javax.swing.GroupLayout(panelBtnGestRes);
        panelBtnGestRes.setLayout(panelBtnGestResLayout);
        panelBtnGestResLayout.setHorizontalGroup(
            panelBtnGestResLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBtnGestResLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnGestRes, javax.swing.GroupLayout.PREFERRED_SIZE, 677, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );
        panelBtnGestResLayout.setVerticalGroup(
            panelBtnGestResLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBtnGestResLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnGestRes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setMaximumSize(new java.awt.Dimension(507, 128));
        jPanel3.setMinimumSize(new java.awt.Dimension(507, 128));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        panelBtnPB.setBackground(new java.awt.Color(29, 29, 29));
        panelBtnPB.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnGestBP.setBackground(new java.awt.Color(255, 255, 255));
        btnGestBP.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        btnGestBP.setForeground(new java.awt.Color(204, 204, 204));
        btnGestBP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/esprit/rt/images/bp001.png"))); // NOI18N
        btnGestBP.setText("Gestion des bon plans");
        btnGestBP.setMaximumSize(new java.awt.Dimension(507, 128));
        btnGestBP.setMinimumSize(new java.awt.Dimension(507, 128));
        btnGestBP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGestBPMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnsMouseEntred(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnsMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelBtnPBLayout = new javax.swing.GroupLayout(panelBtnPB);
        panelBtnPB.setLayout(panelBtnPBLayout);
        panelBtnPBLayout.setHorizontalGroup(
            panelBtnPBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBtnPBLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnGestBP, javax.swing.GroupLayout.PREFERRED_SIZE, 602, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(97, Short.MAX_VALUE))
        );
        panelBtnPBLayout.setVerticalGroup(
            panelBtnPBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBtnPBLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnGestBP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        panelBtnQuitter.setBackground(new java.awt.Color(29, 29, 29));
        panelBtnQuitter.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnQuitter.setForeground(new java.awt.Color(204, 204, 204));
        btnQuitter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/esprit/rt/images/exit001.png"))); // NOI18N
        btnQuitter.setText("Quitter");
        btnQuitter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnQuitterMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnsMouseEntred(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnsMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelBtnQuitterLayout = new javax.swing.GroupLayout(panelBtnQuitter);
        panelBtnQuitter.setLayout(panelBtnQuitterLayout);
        panelBtnQuitterLayout.setHorizontalGroup(
            panelBtnQuitterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBtnQuitterLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnQuitter, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelBtnQuitterLayout.setVerticalGroup(
            panelBtnQuitterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBtnQuitterLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnQuitter)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(panelBtnPB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(panelBtnQuitter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(mainPanelLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(panelBtnGestRes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, mainPanelLayout.createSequentialGroup()
                            .addGap(16, 16, 16)
                            .addComponent(panelBtnGestRest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(448, 448, 448)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(panelBtnGestRest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(panelBtnGestRes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(panelBtnPB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panelBtnQuitter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(95, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnsMouseEntred(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnsMouseEntred
        JLabel tmp = (JLabel) evt.getComponent();
        this.setCursor (Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        tmp.setFont(btnGestRes.getFont().deriveFont(Font.BOLD));
        tmp.setFont(btnGestRes.getFont().deriveFont(0,36));
        tmp.getParent().setBackground(Color.decode("#2f2f2f"));
        tmp.setForeground(Color.decode("#f4ef5d"));
        if (tmp.equals(btnGestRest))
        tmp.setIcon( new ImageIcon( this.getClass().getResource("/esprit/rt/images/restaurant000.png") ));
        if (tmp.equals(btnGestRes))
        tmp.setIcon( new ImageIcon( this.getClass().getResource("/esprit/rt/images/menu000.png") ));
        if (tmp.equals(btnGestBP))
        tmp.setIcon( new ImageIcon( this.getClass().getResource("/esprit/rt/images/bp000.png") ));
        if (tmp.equals(btnQuitter))
        tmp.setIcon( new ImageIcon( this.getClass().getResource("/esprit/rt/images/exit000.png") ));
    }//GEN-LAST:event_btnsMouseEntred

    private void btnsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnsMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnsMouseEntered

    private void btnsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnsMouseExited
        JLabel tmp = (JLabel) evt.getComponent();
        this.setCursor (Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
        evt.getComponent().setFont(btnGestRes.getFont().deriveFont(Font.PLAIN));
        evt.getComponent().setFont(btnGestRes.getFont().deriveFont(0,32));
        tmp.getParent().setBackground(Color.decode("#1d1d1d"));
        tmp.setForeground(Color.decode("#cccccc"));
        if (tmp.equals(btnGestRest))
        tmp.setIcon( new ImageIcon( this.getClass().getResource("/esprit/rt/images/restaurant001.png") ));
        if (tmp.equals(btnGestRes))
        tmp.setIcon( new ImageIcon( this.getClass().getResource("/esprit/rt/images/menu001.png") ));
        if (tmp.equals(btnGestBP))
        tmp.setIcon( new ImageIcon( this.getClass().getResource("/esprit/rt/images/bp001.png") ));
        if (tmp.equals(btnQuitter))
        tmp.setIcon( new ImageIcon( this.getClass().getResource("/esprit/rt/images/exit001.png") ));
    }//GEN-LAST:event_btnsMouseExited

    private void btnQuitterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQuitterMouseClicked
        System.exit(0);
    }//GEN-LAST:event_btnQuitterMouseClicked

    private void goToRest(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_goToRest
        new ConsultRestaurant().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_goToRest

    private void btnGestResMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGestResMouseClicked
        // TODO add your handling code here:
        new ConsultReservation().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnGestResMouseClicked

    private void btnGestBPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGestBPMouseClicked
        // TODO add your handling code here:
        new ConsultBonPlan().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnGestBPMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RestaurateurMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RestaurateurMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RestaurateurMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RestaurateurMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new RestaurateurMainMenu().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(RestaurateurMainMenu.class.getName()).log(Level.SEVERE, null, ex);
                } 
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnGestBP;
    private javax.swing.JLabel btnGestRes;
    private javax.swing.JLabel btnGestRest;
    private javax.swing.JLabel btnQuitter;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel panelBtnGestRes;
    private javax.swing.JPanel panelBtnGestRest;
    private javax.swing.JPanel panelBtnPB;
    private javax.swing.JPanel panelBtnQuitter;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
